[package]
name = "multy"
version = "0.1.0"
authors = ["Jerrain Yohann <kryod@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"
rocket-multipart-form-data = "0.7.2"
rand = "0.7.2"
image = "0.22.2"