name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  Clippy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --no-deps -- -W warnings
  
  Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
